
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: chengzijieczj (https://sketchfab.com/chengzijieczj)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/european-and-american-game-scencemagic-portal-31182bdc05dd40ddbc7f284297e8f225
Title: European and American game scence~Magic portal
*/
'use client'
import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { Group, Mesh, Object3D, Material } from 'three'
import { GLTF } from 'three-stdlib'

// useGLTF.preload('/european_and_american_game_scencemagic_portal.glb')

type GLTFResult = GLTF & {
  nodes: {
    Plane001_shi_aiStandardSurface1SG_0: Mesh
    Sphere001__0: Mesh
    polySurface1_shi_aiStandardSurface4SG_0: Mesh
    polySurface2_shi_aiStandardSurface4SG_0: Mesh
    shi_Group31753_shi_aiStandardSurface4SG_0: Mesh
    shi_Group31754_shi_aiStandardSurface4SG_0: Mesh
    shi_Group31756_shi_aiStandardSurface4SG_0: Mesh
    shi_Group31757_shi_aiStandardSurface4SG_0: Mesh
    shi_Group21994_shi_aiStandardSurface2SG_0: Mesh
    shi_Group31758_shi_aiStandardSurface2SG_0: Mesh
    shi_Group31759_shi_aiStandardSurface2SG_0: Mesh
    shi_Group31755_shi_aiStandardSurface2SG_0: Mesh
    shi_Group31760_shi_aiStandardSurface2SG_0: Mesh
    shi_Group31761_shi_aiStandardSurface2SG_0: Mesh
    shi_Group31762_shi_aiStandardSurface2SG_0: Mesh
    shi_Group31763_shi_aiStandardSurface2SG_0: Mesh
    shi_Group31764_shi_aiStandardSurface2SG_0: Mesh
    shi_Group31765_shi_aiStandardSurface2SG_0: Mesh
  }
  materials: {
    shi_aiStandardSurface1SG: Material
    Sphere001__0: Material
    shi_aiStandardSurface4SG: Material
    shi_aiStandardSurface2SG: Material
  }
}

interface ModelProps {
  botState: string
  actions?: string[]
}

export function PortalModel(props: ModelProps) {
  const group = useRef<Group>(null)
  const { nodes, materials, animations } = useGLTF('/european_and_american_game_scencemagic_portal.glb') as GLTFResult
  const { actions: animationActions } = useAnimations(animations, group)

  useEffect(() => {
    console.log('animationActions', animationActions)
    const availableActions = props.actions?.map(actionName => animationActions[actionName])
      .filter(action => action !== null) || []

    availableActions.forEach(action => {
      action?.reset().fadeIn(0.5).play()
    })

    return () => {
      availableActions.forEach(action => action?.fadeOut(0.5))
    }
  }, [props.actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="lowfbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Plane001"
                  position={[13.833, 81.136, -7.069]}
                  rotation={[0, -1.571, 0]}>
                  <mesh
                    name="Plane001_shi_aiStandardSurface1SG_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane001_shi_aiStandardSurface1SG_0.geometry}
                    material={materials.shi_aiStandardSurface1SG}
                  />
                </group>
                <group
                  name="Sphere001"
                  position={[12.262, 25.99, -5.056]}
                  rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh
                    name="Sphere001__0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Sphere001__0.geometry}
                    material={materials.Sphere001__0}
                  />
                  <group name="polySurface1" position={[-12.262, -5.056, -25.99]}>
                    <mesh
                      name="polySurface1_shi_aiStandardSurface4SG_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.polySurface1_shi_aiStandardSurface4SG_0.geometry}
                      material={materials.shi_aiStandardSurface4SG}
                    />
                  </group>
                  <group name="polySurface2" position={[-12.262, -5.056, -25.99]}>
                    <mesh
                      name="polySurface2_shi_aiStandardSurface4SG_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.polySurface2_shi_aiStandardSurface4SG_0.geometry}
                      material={materials.shi_aiStandardSurface4SG}
                    />
                  </group>
                  <group name="shi_Group31753" position={[-12.262, -5.056, -25.99]}>
                    <mesh
                      name="shi_Group31753_shi_aiStandardSurface4SG_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.shi_Group31753_shi_aiStandardSurface4SG_0.geometry}
                      material={materials.shi_aiStandardSurface4SG}
                    />
                  </group>
                  <group name="shi_Group31754" position={[-12.262, -5.056, -25.99]}>
                    <mesh
                      name="shi_Group31754_shi_aiStandardSurface4SG_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.shi_Group31754_shi_aiStandardSurface4SG_0.geometry}
                      material={materials.shi_aiStandardSurface4SG}
                    />
                  </group>
                  <group name="shi_Group31756" position={[-12.262, -5.056, -25.99]}>
                    <mesh
                      name="shi_Group31756_shi_aiStandardSurface4SG_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.shi_Group31756_shi_aiStandardSurface4SG_0.geometry}
                      material={materials.shi_aiStandardSurface4SG}
                    />
                  </group>
                  <group name="shi_Group31757" position={[-12.262, -5.056, -25.99]}>
                    <mesh
                      name="shi_Group31757_shi_aiStandardSurface4SG_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.shi_Group31757_shi_aiStandardSurface4SG_0.geometry}
                      material={materials.shi_aiStandardSurface4SG}
                    />
                  </group>
                  <group name="shi_Group21994" position={[-12.262, -5.056, -25.99]}>
                    <mesh
                      name="shi_Group21994_shi_aiStandardSurface2SG_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.shi_Group21994_shi_aiStandardSurface2SG_0.geometry}
                      material={materials.shi_aiStandardSurface2SG}
                    />
                  </group>
                  <group name="shi_Group31758" position={[-12.262, -5.056, -25.99]}>
                    <mesh
                      name="shi_Group31758_shi_aiStandardSurface2SG_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.shi_Group31758_shi_aiStandardSurface2SG_0.geometry}
                      material={materials.shi_aiStandardSurface2SG}
                    />
                  </group>
                  <group name="shi_Group31759" position={[-12.262, -5.056, -25.99]}>
                    <mesh
                      name="shi_Group31759_shi_aiStandardSurface2SG_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.shi_Group31759_shi_aiStandardSurface2SG_0.geometry}
                      material={materials.shi_aiStandardSurface2SG}
                    />
                  </group>
                  <group name="shi_Group31755" position={[-12.262, -5.056, 34.875]}>
                    <mesh
                      name="shi_Group31755_shi_aiStandardSurface2SG_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.shi_Group31755_shi_aiStandardSurface2SG_0.geometry}
                      material={materials.shi_aiStandardSurface2SG}
                    />
                  </group>
                  <group name="shi_Group31760" position={[-12.262, -5.056, -39.749]}>
                    <mesh
                      name="shi_Group31760_shi_aiStandardSurface2SG_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.shi_Group31760_shi_aiStandardSurface2SG_0.geometry}
                      material={materials.shi_aiStandardSurface2SG}
                    />
                  </group>
                  <group name="shi_Group31761" position={[-12.262, -5.056, -25.99]}>
                    <mesh
                      name="shi_Group31761_shi_aiStandardSurface2SG_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.shi_Group31761_shi_aiStandardSurface2SG_0.geometry}
                      material={materials.shi_aiStandardSurface2SG}
                    />
                  </group>
                  <group name="shi_Group31762" position={[-12.262, -5.056, -25.99]}>
                    <mesh
                      name="shi_Group31762_shi_aiStandardSurface2SG_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.shi_Group31762_shi_aiStandardSurface2SG_0.geometry}
                      material={materials.shi_aiStandardSurface2SG}
                    />
                  </group>
                  <group name="shi_Group31763" position={[-12.262, -5.056, -25.99]}>
                    <mesh
                      name="shi_Group31763_shi_aiStandardSurface2SG_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.shi_Group31763_shi_aiStandardSurface2SG_0.geometry}
                      material={materials.shi_aiStandardSurface2SG}
                    />
                  </group>
                  <group name="shi_Group31764" position={[-12.262, -5.056, -25.99]}>
                    <mesh
                      name="shi_Group31764_shi_aiStandardSurface2SG_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.shi_Group31764_shi_aiStandardSurface2SG_0.geometry}
                      material={materials.shi_aiStandardSurface2SG}
                    />
                  </group>
                  <group name="shi_Group31765" position={[-12.262, -5.056, -25.99]}>
                    <mesh
                      name="shi_Group31765_shi_aiStandardSurface2SG_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.shi_Group31765_shi_aiStandardSurface2SG_0.geometry}
                      material={materials.shi_aiStandardSurface2SG}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

